[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm build"
watchPatterns = [
    "/platform/apps/**",
    "/platform/packages/**",
    "/platform/pnpm-lock.yaml",
    "/platform/package.json",
    "/platform/turbo.json"
]

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
